package com.itheima.crm.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2016-12-24T15:11:46.541+08:00
 * Generated source version: 2.4.2
 * 
 */
@WebService(targetNamespace = "http://webservice.itheima.com/", name = "CustomerService")
@XmlSeeAlso({})
public interface CustomerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindCustomerByTelephone")
    @WebMethod
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindCustomerByTelephoneResponse")
    public com.itheima.crm.client.Customer findCustomerByTelephone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomerNotAssociation", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindCustomerNotAssociation")
    @WebMethod
    @ResponseWrapper(localName = "findCustomerNotAssociationResponse", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindCustomerNotAssociationResponse")
    public java.util.List<com.itheima.crm.client.Customer> findCustomerNotAssociation();

    @RequestWrapper(localName = "assignCustomersToDecidedzone", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.AssignCustomersToDecidedzone")
    @WebMethod
    @ResponseWrapper(localName = "assignCustomersToDecidedzoneResponse", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.AssignCustomersToDecidedzoneResponse")
    public void assignCustomersToDecidedzone(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindAll")
    @WebMethod
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindAllResponse")
    public java.util.List<com.itheima.crm.client.Customer> findAll();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByDecidedzoneId", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindCustomerByDecidedzoneId")
    @WebMethod
    @ResponseWrapper(localName = "findCustomerByDecidedzoneIdResponse", targetNamespace = "http://webservice.itheima.com/", className = "com.itheima.crm.client.FindCustomerByDecidedzoneIdResponse")
    public java.util.List<com.itheima.crm.client.Customer> findCustomerByDecidedzoneId(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
